//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Euler_Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Euler_Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001:https://raw.githubusercontent.com/ROXER94/Project-Euler/master/001/1%20-%203%265Multiples.py
        ///002:https://raw.githubusercontent.com/ROXER94/Project-Euler/master/002/2%20-%20EvenFibonacciSum.py
        ///003:https://raw.githubusercontent.com/ROXER94/Project-Euler/master/003/3%20-%20PrimeFactors.py
        ///004:https://raw.githubusercontent.com/ROXER94/Project-Euler/master/004/4%20-%20LargestPalindromeProduct.py
        ///005:https://raw.githubusercontent.com/ROXER94/Project-Euler/master/005/5%20-%20SmallestMultiple.py
        ///006:https: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PythonURL {
            get {
                return ResourceManager.GetString("PythonURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 090: 16 Oct 18 (23:17)
        ///493: 10 Sep 18 (22:05)
        ///191: 23 Mar 18 (21:52)
        ///174: 23 Mar 18 (19:46)
        ///407: 22 Mar 18 (20:26)
        ///451: 20 Mar 18 (22:20)
        ///622: 16 Mar 18 (21:10)
        ///548: 06 Jun 17 (23:12)
        ///604: 28 May 17 (22:55)
        ///190: 13 May 17 (22:09)
        ///101: 07 May 17 (14:12)
        ///188: 07 May 17 (00:58)
        ///293: 06 May 17 (16:44)
        ///205: 06 May 17 (01:48)
        ///204: 05 May 17 (22:56)
        ///133: 29 Apr 17 (17:07)
        ///175: 29 Apr 17 (00:48)
        ///169: 28 Apr 17 (21:35)
        ///176: 24 Apr 17 (17:47)
        ///130: 23 Apr 17 (03:12)
        ///129: 23 Apr 17 (02:26)
        ///303: 22  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string roxer94_history {
            get {
                return ResourceManager.GetString("roxer94_history", resourceCulture);
            }
        }
    }
}
